
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int hash = 3;
  public static final int dollar = 4;
  public static final int ptyComa = 16;
  public static final int dosPts = 15;
  public static final int corcheteA = 22;
  public static final int underScore = 24;
  public static final int coma = 11;
  public static final int amberson = 6;
  public static final int porcentaje = 5;
  public static final int conj = 30;
  public static final int or = 26;
  public static final int slashInverso = 29;
  public static final int sombrero = 23;
  public static final int menor = 17;
  public static final int guion = 12;
  public static final int punto = 13;
  public static final int llaveC = 27;
  public static final int admiracion = 2;
  public static final int igual = 18;
  public static final int EOF = 0;
  public static final int letra = 32;
  public static final int llaveA = 25;
  public static final int simbolo = 33;
  public static final int slash = 14;
  public static final int colocho = 28;
  public static final int error = 1;
  public static final int entero = 31;
  public static final int parentesisC = 8;
  public static final int arroba = 21;
  public static final int asterisco = 9;
  public static final int interrogacion = 20;
  public static final int mas = 10;
  public static final int parentesisA = 7;
  public static final int identificador = 34;
  public static final int mayor = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "admiracion",
  "hash",
  "dollar",
  "porcentaje",
  "amberson",
  "parentesisA",
  "parentesisC",
  "asterisco",
  "mas",
  "coma",
  "guion",
  "punto",
  "slash",
  "dosPts",
  "ptyComa",
  "menor",
  "igual",
  "mayor",
  "interrogacion",
  "arroba",
  "corcheteA",
  "sombrero",
  "underScore",
  "llaveA",
  "or",
  "llaveC",
  "colocho",
  "slashInverso",
  "conj",
  "entero",
  "letra",
  "simbolo",
  "identificador"
  };
}

